behaviors:
  LawnMower:
    trainer_type: ppo
    threaded: true
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: "D:\\EVERYTHING\\UnityProject\\SimpleLawn\\Demos\\LawnMowerDemo.demo"
    behavioral_cloning:
      strength: 0.5
      demo_path: "D:\\EVERYTHING\\UnityProject\\SimpleLawn\\Demos\\LawnMowerDemo.demo"
    keep_checkpoints: 10
    max_steps: 2000000
    time_horizon: 64
    summary_freq: 10000


