behaviors:
  LawnMower:
    trainer_type: ppo
    threaded: true
    hyperparameters:
      batch_size: 1024
      buffer_size: 16384
      learning_rate: 0.0001
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 12
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 2000000
    checkpoint_interval: 100000
    time_horizon: 32
    summary_freq: 10000



